# 0. Разминка

Немного вспомним, чем именно мы занимались на предыдущем семинаре! 

<img src="https://steemitimages.com/0x0/https://media.makeameme.org/created/repeat-repeat-repeat-5984a6.jpg" height="350" width="350">

Начнём с разминочной задачки :) 

## Разминочная задачка

У Дори в глубинах океана есть кучка камней. Часть камней из этой кучки драгоценные. Недавно она пересчитала все драгоценные и забыла сколько их. Чтобы больше не забывать, Дори решила написать на питоне функцию, которая будет считать камни за неё.

Напишите на python функцию, которая принимает на вход список драгоценных камней $J$ и список камней, которые есть у Дори $S$. На выход функция возвращает число драгоценных камней в запасах Дори.

__Примеры:__ 

> Input: J = "aA", S = "aAAbbbb" <br />
Output: 3

Тут драгоценными считаются камни a и A. У Дори есть камни aAAbbbb. Среди них три драгоценных, aAA.

>Input: J = "z", S = "ZZ" <br />
Output: 0

Драгоценными мы считаем только камень z. У Дори два камня, оба обычные.

In [1]:
def numJewelsInStones(J, S):
    
    counter = 0
    J = set(J)
    
    for stone in S:
        if stone in J:
            counter += 1
    
    return counter

In [2]:
J = "aAaA"
S = "aAAbbbb"

numJewelsInStones(J, S)

3

# 1. Пакеты

![](http://advaitaworld.com/uploads/images/00/13/28/2012/06/15/36a8a1.png)

Разработчики языка Python придерживаются определённой философии программирования, называемой «The Zen of Python» («Дзен Питона», или «Дзен Пайтона»). 

Её текст можно поспотреть с помощью комнды import this (работает один раз за сессию).

In [3]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

Команда import позволяет подгрузить не только философию, но и какой-нибудь пакет с какими-нибудь командами.

Попробуем подгрузить несколькими разными способами пакет math.

In [4]:
import math 
math.sqrt(4)

2.0

При таком способе загрузки обращение к каждой команде модуля делается через точку. В Python работает табуляция. Если написать название модуля, поставить точку, а после нажать Tab, то Jupyter Notebook подскажет какие ещё команды есть внутри модуля.

In [5]:
math.sin(20)

0.9129452507276277

Приведенный синтаксис может оказаться неудобным, если вам часто приходится вызывать какие-то математические функции. Чтобы не писать каждый раз слово «math», можно импортировать из модуля конкретные функции.

In [6]:
from math import sqrt

sqrt(4)

2.0

По аналогии можно импортировать из модуля абсолютно все функции, которые в нём есть с помощью команды *

In [8]:
from math import * # Не стоит так делать, это может создать конфликт имён
pi

3.141592653589793

Также можно подгрузить какой-нибудь модуль или пакет, но при этом изменить у него название на более короткое и пользоваться им.

In [9]:
import math as mh
mh.sqrt(4)

2.0

# 2. Все любят панд

Давайте подгрузим пакет для работы с таблицами, [pandas](http://pandas.pydata.org/) и попробуем немного поработать с данными.

## 2.1 Смотрим на данные

In [10]:
import pandas as pd  # Подгружаем пакет для работы с таблицами

По имени `pd` нам теперь доступна куча команд для работы с таблицами. Давайте подгрузим данные и посмотрим что лежит внутри нашей таблички. Делать это будем командой [pd.read_csv().](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html#pandas.read_csv)

Аргументов у нее очень много, критически важные:

 - **filepath_or_buffer** - текстовая строка с названием (адресом) файла
 - **sep** - разделитель между данными
 - **header** - номер строки, в которой в файле указаны названия столбцов, None, если нет
 - **names** - список с названиями колонок
 - **index_col** - или номер столбца, или список,  или ничего - названия строк

In [14]:
df = pd.read_csv('sem_2_oscars_df.csv')

In [15]:
# Вывести первые 4 строки
df.head(4)

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",...,Certified-Fresh,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067
1,1,7th Heaven,1927/28,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19ed3295-a878-4fd2-8e60-5cd7b5f93dad
2,2,The Racket,1927/28,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3111c2d8-0908-4093-8ff3-99c89f2f2f08
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",...,Rotten,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236

In [16]:
# Вывести последние 5 строк
df.tail()

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
566,566,Mank,2020,"Ceán Chaffin, Eric Roth, and Douglas Urbanski",Nominee,2020,131,"Biography,Comedy,Drama",6.9,"65,380",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47d4ae4f-e782-4cd9-9508-4a07302b1c1a
567,567,Minari,2020,Christina Oh,Nominee,2020,115,Drama,7.5,"57,976",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7262b3a8-214d-4205-985c-70e0860f3236
568,568,Promising Young Woman,2020,"Ben Browning, Ashley Fox, Emerald Fennell, and...",Nominee,2020,113,"Crime,Drama,Thriller",7.5,"122,269",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d64c669b-7a73-496a-bddb-19cb09264371
569,569,Sound of Metal,2020,Bert Hamelinck and Sacha Ben Harroche,Nominee,2019,120,"Drama,Music",7.8,"102,807",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,647357e9-c067-46bd-aaeb-24d4344ec124
570,570,The Trial of the Chicago 7,2020,Marc Platt and Stuart M. Besser,Nominee,2020,129,"Drama,History,Thriller",7.8,"156,283",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cecbca48-f19c-43f4-81d2-da130facda95

In [17]:
df.head(10)

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",...,Certified-Fresh,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067
1,1,7th Heaven,1927/28,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19ed3295-a878-4fd2-8e60-5cd7b5f93dad
2,2,The Racket,1927/28,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3111c2d8-0908-4093-8ff3-99c89f2f2f08
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",...,Rotten,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236
4,4,Alibi,1928/29,Feature Productions,Nominee,1929,91,"Action,Crime,Romance",5.8,765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609887c2-877c-43a4-b88c-e40e31096a98
5,5,Hollywood Revue,1928/29,Metro-Goldwyn-Mayer,Nominee,1929,130,"Comedy,Music",5.7,"2,004",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,689f22d5-a700-4ce1-b9be-65652f32c186
6,6,In Old Arizona,1928/29,Fox,Nominee,1928,95,Western,5.6,"1,019",...,Rotten,56.0,9.0,Spilled,38.0,356.0,2.0,5.0,4.0,a0644f19-a136-44c2-ab5d-50978ef19608
7,7,The Patriot,1928/29,Paramount Famous Lasky,Nominee,1928,113,"Drama,History,Thriller",7.4,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5d4ef7bd-2f81-47f3-9305-2c8fe140d4e4
8,8,All Quiet on the Western Front,1929/30,Universal,Winner,1930,152,"Drama,War",8.1,"59,214",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,281742f9-3b4e-480d-b704-c8c15de6b721
9,9,The Big House,1929/30,Cosmopolitan,Nominee,1930,87,"Crime,Drama,Thriller",7.1,"2,079",...,Fresh,75.0,8.0,Upright,69.0,323.0,0.0,6.0,2.0,297aa285-29d7-4a22-b833-c5632ab3e562

In [18]:
df

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",...,Certified-Fresh,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067
1,1,7th Heaven,1927/28,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19ed3295-a878-4fd2-8e60-5cd7b5f93dad
2,2,The Racket,1927/28,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3111c2d8-0908-4093-8ff3-99c89f2f2f08
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",...,Rotten,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236
4,4,Alibi,1928/29,Feature Productions,Nominee,1929,91,"Action,Crime,Romance",5.8,765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609887c2-877c-43a4-b88c-e40e31096a98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,566,Mank,2020,"Ceán Chaffin, Eric Roth, and Douglas Urbanski",Nominee,2020,131,"Biography,Comedy,Drama",6.9,"65,380",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47d4ae4f-e782-4cd9-9508-4a07302b1c1a
567,567,Minari,2020,Christina Oh,Nominee,2020,115,Drama,7.5,"57,976",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7262b3a8-214d-4205-985c-70e0860f3236
568,568,Promising Young Woman,2020,"Ben Browning, Ashley Fox, Emerald Fennell, and...",Nominee,2020,113,"Crime,Drama,Thriller",7.5,"122,269",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d64c669b-7a73-496a-bddb-19cb09264371
569,569,Sound of Metal,2020,Bert Hamelinck and Sacha Ben Harroche,Nominee,2019,120,"Drama,Music",7.8,"102,807",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,647357e9-c067-46bd-aaeb-24d4344ec124
570,570,The Trial of the Chicago 7,2020,Marc Platt and Stuart M. Besser,Nominee,2020,129,"Drama,History,Thriller",7.8,"156,283",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cecbca48-f19c-43f4-81d2-da130facda95

In [19]:
# Типы данных в колонках
# Пандас разделяет три типа данных: целый (int), вещественный (float) и все прочие (object)
df.dtypes

Unnamed: 0                            int64
Film                                 object
Oscar Year                           object
Film Studio/Producer(s)              object
Award                                object
Year of Release                       int64
Movie Time                            int64
Movie Genre                          object
IMDB Rating                         float64
IMDB Votes                           object
Movie Info                           object
Genres                               object
Critic Consensus                     object
Content Rating                       object
Directors                            object
Authors                              object
Actors                               object
Original Release Date                object
Streaming Release Date               object
Production Company                   object
Tomatometer Status                   object
Tomatometer Rating                  float64
Tomatometer Count                   float64
Audience Status                      object
Audience Rating                     float64
Audience Count                      float64
Tomatometer Top Critics Count       float64
Tomatometer Fresh Critics Count     float64
Tomatometer Rotten Critics Count    float64
Film ID                              object
dtype: object

In [20]:
# Посмотреть сводную информацию о таблице
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        571 non-null    int64
 1   Film                              571 non-null    object
 2   Oscar Year                        571 non-null    object
 3   Film Studio/Producer(s)           571 non-null    object
 4   Award                             571 non-null    object
 5   Year of Release                   571 non-null    int64
 6   Movie Time                        571 non-null    int64
 7   Movie Genre                       571 non-null    object
 8   IMDB Rating                       571 non-null    float64
 9   IMDB Votes                        571 non-null    object
 10  Movie Info                        438 non-null    object
 11  Genres                            439 non-null    object
 12  Critic Consensus                  339 non-null    object
 13  Content Rating                    439 non-null    object
 14  Directors                         437 non-null    object
 15  Authors                           437 non-null    object
 16  Actors                            439 non-null    object
 17  Original Release Date             439 non-null    object
 18  Streaming Release Date            438 non-null    object
 19  Production Company                439 non-null    object
 20  Tomatometer Status                439 non-null    object
 21  Tomatometer Rating                439 non-null    float64
 22  Tomatometer Count                 439 non-null    float64
 23  Audience Status                   436 non-null    object
 24  Audience Rating                   439 non-null    float64
 25  Audience Count                    439 non-null    float64
 26  Tomatometer Top Critics Count     439 non-null    float64
 27  Tomatometer Fresh Critics Count   439 non-null    float64
 28  Tomatometer Rotten Critics Count  439 non-null    float64
 29  Film ID                           571 non-null    object
dtypes: float64(8), int64(3), object(19)
memory usage: 134.0+ KB

В табличке есть огромное количество самых разных переменных. Их названия довольно интуитивны. Будем разбираться с тем, за что отвечает какая колонка по мере необходимости.

---

Есть несколько методов, которые мы используем сразу, как загрузили файл:
- [head()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html): выводит первые 5 строк таблицы. Если задать в скобках число, то покажет ровно столько строк :)
- [info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html): показывает сводную информацию о таблице; сколько записей, сколько колонок, сколько непустых записей в таблице, 
- [tail()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html): работает как head(), только наоборот, печатает с конца

На всякий случай, это **методы**. Их можно применять к датафрейму и столбцу, т.е. используем их так: <br>
**[Имя датафрейма].[Название метода с круглыми скобками]**
- df.head()
- df.tail()
- df.info()

----


На основную информацию по столбцам можно посмотреть с помощью метода `.info()`. Напротив каждого названия столбца можно увидеть, сколько в нём заполненных ячеек.

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        571 non-null    int64
 1   Film                              571 non-null    object
 2   Oscar Year                        571 non-null    object
 3   Film Studio/Producer(s)           571 non-null    object
 4   Award                             571 non-null    object
 5   Year of Release                   571 non-null    int64
 6   Movie Time                        571 non-null    int64
 7   Movie Genre                       571 non-null    object
 8   IMDB Rating                       571 non-null    float64
 9   IMDB Votes                        571 non-null    object
 10  Movie Info                        438 non-null    object
 11  Genres                            439 non-null    object
 12  Critic Consensus                  339 non-null    object
 13  Content Rating                    439 non-null    object
 14  Directors                         437 non-null    object
 15  Authors                           437 non-null    object
 16  Actors                            439 non-null    object
 17  Original Release Date             439 non-null    object
 18  Streaming Release Date            438 non-null    object
 19  Production Company                439 non-null    object
 20  Tomatometer Status                439 non-null    object
 21  Tomatometer Rating                439 non-null    float64
 22  Tomatometer Count                 439 non-null    float64
 23  Audience Status                   436 non-null    object
 24  Audience Rating                   439 non-null    float64
 25  Audience Count                    439 non-null    float64
 26  Tomatometer Top Critics Count     439 non-null    float64
 27  Tomatometer Fresh Critics Count   439 non-null    float64
 28  Tomatometer Rotten Critics Count  439 non-null    float64
 29  Film ID                           571 non-null    object
dtypes: float64(8), int64(3), object(19)
memory usage: 134.0+ KB

Методов вроде `head()` и `info()` у табличек есть очень много. Давайте попробуем самые простые из них: 

### Задание 1.1:

- Выведите на экран первые 10 строк таблички 
- Выведите последние 5 строк таблички (метод `tail()`)

In [22]:
df.head(10)

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",...,Certified-Fresh,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067
1,1,7th Heaven,1927/28,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19ed3295-a878-4fd2-8e60-5cd7b5f93dad
2,2,The Racket,1927/28,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3111c2d8-0908-4093-8ff3-99c89f2f2f08
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",...,Rotten,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236
4,4,Alibi,1928/29,Feature Productions,Nominee,1929,91,"Action,Crime,Romance",5.8,765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609887c2-877c-43a4-b88c-e40e31096a98
5,5,Hollywood Revue,1928/29,Metro-Goldwyn-Mayer,Nominee,1929,130,"Comedy,Music",5.7,"2,004",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,689f22d5-a700-4ce1-b9be-65652f32c186
6,6,In Old Arizona,1928/29,Fox,Nominee,1928,95,Western,5.6,"1,019",...,Rotten,56.0,9.0,Spilled,38.0,356.0,2.0,5.0,4.0,a0644f19-a136-44c2-ab5d-50978ef19608
7,7,The Patriot,1928/29,Paramount Famous Lasky,Nominee,1928,113,"Drama,History,Thriller",7.4,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5d4ef7bd-2f81-47f3-9305-2c8fe140d4e4
8,8,All Quiet on the Western Front,1929/30,Universal,Winner,1930,152,"Drama,War",8.1,"59,214",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,281742f9-3b4e-480d-b704-c8c15de6b721
9,9,The Big House,1929/30,Cosmopolitan,Nominee,1930,87,"Crime,Drama,Thriller",7.1,"2,079",...,Fresh,75.0,8.0,Upright,69.0,323.0,0.0,6.0,2.0,297aa285-29d7-4a22-b833-c5632ab3e562

In [23]:
df.tail(5)

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
566,566,Mank,2020,"Ceán Chaffin, Eric Roth, and Douglas Urbanski",Nominee,2020,131,"Biography,Comedy,Drama",6.9,"65,380",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47d4ae4f-e782-4cd9-9508-4a07302b1c1a
567,567,Minari,2020,Christina Oh,Nominee,2020,115,Drama,7.5,"57,976",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7262b3a8-214d-4205-985c-70e0860f3236
568,568,Promising Young Woman,2020,"Ben Browning, Ashley Fox, Emerald Fennell, and...",Nominee,2020,113,"Crime,Drama,Thriller",7.5,"122,269",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d64c669b-7a73-496a-bddb-19cb09264371
569,569,Sound of Metal,2020,Bert Hamelinck and Sacha Ben Harroche,Nominee,2019,120,"Drama,Music",7.8,"102,807",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,647357e9-c067-46bd-aaeb-24d4344ec124
570,570,The Trial of the Chicago 7,2020,Marc Platt and Stuart M. Besser,Nominee,2020,129,"Drama,History,Thriller",7.8,"156,283",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cecbca48-f19c-43f4-81d2-da130facda95

----------
### Поля
Кроме методов, у датафреймом есть еще поля. Это справочная информация о датафрейме. Список полей
<a href="https://pandas.pydata.org/pandas-docs/stable/reference/frame.html"> здесь </a>.

Чаще всего мы используем поля: 
- **columns**: названия колонок
- **index**: названия строк
- **shape**: размеры датафрейма, кол-во строк и столбцов

Использование:

**[Имя датафрейма].[Имя поля]**

- df.columns
- df.index
- df.shape

Обратите внимание: нет круглых скобок!

In [24]:
# Число строк и столбцов
df.shape

(571, 30)

In [25]:
df

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",...,Certified-Fresh,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067
1,1,7th Heaven,1927/28,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19ed3295-a878-4fd2-8e60-5cd7b5f93dad
2,2,The Racket,1927/28,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3111c2d8-0908-4093-8ff3-99c89f2f2f08
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",...,Rotten,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236
4,4,Alibi,1928/29,Feature Productions,Nominee,1929,91,"Action,Crime,Romance",5.8,765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609887c2-877c-43a4-b88c-e40e31096a98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,566,Mank,2020,"Ceán Chaffin, Eric Roth, and Douglas Urbanski",Nominee,2020,131,"Biography,Comedy,Drama",6.9,"65,380",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47d4ae4f-e782-4cd9-9508-4a07302b1c1a
567,567,Minari,2020,Christina Oh,Nominee,2020,115,Drama,7.5,"57,976",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7262b3a8-214d-4205-985c-70e0860f3236
568,568,Promising Young Woman,2020,"Ben Browning, Ashley Fox, Emerald Fennell, and...",Nominee,2020,113,"Crime,Drama,Thriller",7.5,"122,269",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d64c669b-7a73-496a-bddb-19cb09264371
569,569,Sound of Metal,2020,Bert Hamelinck and Sacha Ben Harroche,Nominee,2019,120,"Drama,Music",7.8,"102,807",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,647357e9-c067-46bd-aaeb-24d4344ec124
570,570,The Trial of the Chicago 7,2020,Marc Platt and Stuart M. Besser,Nominee,2020,129,"Drama,History,Thriller",7.8,"156,283",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cecbca48-f19c-43f4-81d2-da130facda95

### Задание 1.2: 
- Выясните сколько в таблице строк и столбцов (свойство `shape`)
- Выведите на экран названия всех колонок таблицы (свойство `columns`)

In [26]:
df.shape

(571, 30)

In [27]:
df.index # Названия строк

RangeIndex(start=0, stop=571, step=1)

In [33]:
df.columns # Названия столбцов

Index(['Unnamed: 0', 'Film', 'Oscar Year', 'Film Studio/Producer(s)', 'Award',
       'Year of Release', 'Movie Time', 'Movie Genre', 'IMDB Rating',
       'IMDB Votes', 'Movie Info', 'Genres', 'Critic Consensus',
       'Content Rating', 'Directors', 'Authors', 'Actors',
       'Original Release Date', 'Streaming Release Date', 'Production Company',
       'Tomatometer Status', 'Tomatometer Rating', 'Tomatometer Count',
       'Audience Status', 'Audience Rating', 'Audience Count',
       'Tomatometer Top Critics Count', 'Tomatometer Fresh Critics Count',
       'Tomatometer Rotten Critics Count', 'Film ID'],
      dtype='object')

## 2.2 Базовые навыки по работе с табличками

### Выбор колонки

Чтобы вытащить столбец, к нему нужно через квадратные скобки обратиться по имени.

In [34]:
df['Film']

0                           Wings
1                      7th Heaven
2                      The Racket
3             The Broadway Melody
4                           Alibi
                  ...
566                          Mank
567                        Minari
568         Promising Young Woman
569                Sound of Metal
570    The Trial of the Chicago 7
Name: Film, Length: 571, dtype: object

In [35]:
df.Film

0                           Wings
1                      7th Heaven
2                      The Racket
3             The Broadway Melody
4                           Alibi
                  ...
566                          Mank
567                        Minari
568         Promising Young Woman
569                Sound of Metal
570    The Trial of the Chicago 7
Name: Film, Length: 571, dtype: object

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
# Series = один изъятый столбец
# DataFrame = несколько столбцов
type(df.Film)

pandas.core.series.Series

Можно вытащить сразу несколько колонок и применить к ним какой-нибудь метод:

In [38]:
# Обратите внимание, что в квадратные скобки мы вписали только 1 объект - лист с названиями колонок
df[['Film', 'Oscar Year', 'Audience Status']]

                           Film Oscar Year Audience Status
0                         Wings    1927/28         Upright
1                    7th Heaven    1927/28             NaN
2                    The Racket    1927/28             NaN
3           The Broadway Melody    1928/29         Spilled
4                         Alibi    1928/29             NaN
..                          ...        ...             ...
566                        Mank       2020             NaN
567                      Minari       2020             NaN
568       Promising Young Woman       2020             NaN
569              Sound of Metal       2020             NaN
570  The Trial of the Chicago 7       2020             NaN

[571 rows x 3 columns]

Можно создавать новые колонки.

In [39]:
# Создаст колонку Year + 100, в которой будут значения из колонки Year of Release + 100
df['Year + 100'] = df['Year of Release'] + 100

In [40]:
df

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID,Year + 100
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",...,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067,2027
1,1,7th Heaven,1927/28,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19ed3295-a878-4fd2-8e60-5cd7b5f93dad,2027
2,2,The Racket,1927/28,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3111c2d8-0908-4093-8ff3-99c89f2f2f08,2028
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",...,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236,2029
4,4,Alibi,1928/29,Feature Productions,Nominee,1929,91,"Action,Crime,Romance",5.8,765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609887c2-877c-43a4-b88c-e40e31096a98,2029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,566,Mank,2020,"Ceán Chaffin, Eric Roth, and Douglas Urbanski",Nominee,2020,131,"Biography,Comedy,Drama",6.9,"65,380",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47d4ae4f-e782-4cd9-9508-4a07302b1c1a,2120
567,567,Minari,2020,Christina Oh,Nominee,2020,115,Drama,7.5,"57,976",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7262b3a8-214d-4205-985c-70e0860f3236,2120
568,568,Promising Young Woman,2020,"Ben Browning, Ashley Fox, Emerald Fennell, and...",Nominee,2020,113,"Crime,Drama,Thriller",7.5,"122,269",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d64c669b-7a73-496a-bddb-19cb09264371,2120
569,569,Sound of Metal,2020,Bert Hamelinck and Sacha Ben Harroche,Nominee,2019,120,"Drama,Music",7.8,"102,807",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,647357e9-c067-46bd-aaeb-24d4344ec124,2119
570,570,The Trial of the Chicago 7,2020,Marc Platt and Stuart M. Besser,Nominee,2020,129,"Drama,History,Thriller",7.8,"156,283",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cecbca48-f19c-43f4-81d2-da130facda95,2120

### Индексация

In [51]:
# Если хотя бы одно имя - loc
df.loc[0, 'Film']

'Wings'

In [52]:
# Если только индексы – iloc
df.iloc[0, 3]

'Famous Players-Lasky'

In [54]:
df.loc[0, "Film"]

'Wings'

In [55]:
df[0, "Film"]

KeyError: (0, 'Film')

In [56]:
df[0, 1]

KeyError: (0, 1)

In [60]:
df.loc[3:10, 'Year of Release']

3     1929
4     1929
5     1929
6     1928
7     1928
8     1930
9     1930
10    1929
Name: Year of Release, dtype: int64

---
### Уникальные значения и частотые таблицы

Очень частой операцией является нахождение уникальных значений в колонке. В зависимости от задачи есть два метода. 
- [unique()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.unique.html): возвращает массив уникальных значений в колонке - к нему можем применять только обычный питон
- [drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html): удаляет дублирующиеся строчки в датафрейме/колонке и возвращает соответственно датафрейм или колонку - к ним можем дальше применять пандасовские методы

- [value_counts()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html): считает частотную таблицу, т.е. сколько раз мы встретили значение в колонке

In [41]:
df['Film'].unique()

array(['Wings', '7th Heaven', 'The Racket', 'The Broadway Melody',
       'Alibi', 'Hollywood Revue', 'In Old Arizona', 'The Patriot',
       'All Quiet on the Western Front', 'The Big House', 'Disraeli',
       'The Divorcee', 'The Love Parade', 'Cimarron', 'East Lynne',
       'The Front Page', 'Skippy', 'Trader Horn', 'Grand Hotel',
       'Arrowsmith', 'Bad Girl', 'The Champ', 'Five Star Final',
       'One Hour with You', 'Shanghai Express', 'The Smiling Lieutenant',
       'Cavalcade', '42nd Street', 'A Farewell to Arms',
       'I Am a Fugitive from a Chain Gang', 'Lady for a Day',
       'Little Women', 'The Private Life of Henry VIII',
       'She Done Him Wrong', "Smilin' Through", 'State Fair',
       'It Happened One Night', 'The Barretts of Wimpole Street',
       'Cleopatra', 'Flirtation Walk', 'The Gay Divorcee',
       'Here Comes the Navy', 'The House of Rothschild',
       'Imitation of Life', 'One Night of Love', 'The Thin Man',
       'Viva Villa!', 'The White Parade', 'Mutiny on the Bounty',
       'Alice Adams', 'Broadway Melody of 1936', 'Captain Blood',
       'David Copperfield', 'The Informer',
       'The Lives of a Bengal Lancer', "A Midsummer Night's Dream",
       'Les Misérables', 'Naughty Marietta', 'Ruggles of Red Gap',
       'Top Hat', 'The Great Ziegfeld', 'Anthony Adverse', 'Dodsworth',
       'Libeled Lady', 'Mr. Deeds Goes to Town', 'Romeo and Juliet',
       'San Francisco', 'The Story of Louis Pasteur',
       'A Tale of Two Cities', 'Three Smart Girls',
       'The Life of Emile Zola', 'The Awful Truth', 'Captains Courageous',
       'Dead End', 'The Good Earth', 'In Old Chicago', 'Lost Horizon',
       'One Hundred Men and a Girl', 'Stage Door', 'A Star Is Born',
       "You Can't Take It with You", 'The Adventures of Robin Hood',
       "Alexander's Ragtime Band", 'Boys Town', 'The Citadel',
       'Four Daughters', 'Grand Illusion', 'Jezebel', 'Pygmalion',
       'Test Pilot', 'Gone with the Wind', 'Dark Victory',
       'Goodbye, Mr. Chips', 'Love Affair',
       'Mr. Smith Goes to Washington', 'Ninotchka', 'Of Mice and Men',
       'Stagecoach', 'The Wizard of Oz', 'Wuthering Heights', 'Rebecca',
       'All This, and Heaven Too', 'Foreign Correspondent',
       'The Grapes of Wrath', 'The Great Dictator', 'Kitty Foyle',
       'The Letter', 'The Long Voyage Home', 'Our Town',
       'The Philadelphia Story', 'How Green Was My Valley',
       'Blossoms in the Dust', 'Citizen Kane', 'Here Comes Mr. Jordan',
       'Hold Back the Dawn', 'The Little Foxes', 'The Maltese Falcon',
       'One Foot in Heaven', 'Sergeant York', 'Suspicion', 'Mrs. Miniver',
       '49th Parallel', 'Kings Row', 'The Magnificent Ambersons',
       'The Pied Piper', 'The Pride of the Yankees', 'Random Harvest',
       'The Talk of the Town', 'Wake Island', 'Yankee Doodle Dandy',
       'Casablanca', 'For Whom the Bell Tolls', 'Heaven Can Wait',
       'The Human Comedy', 'In Which We Serve', 'Madame Curie',
       'The More the Merrier', 'The Ox-Bow Incident',
       'The Song of Bernadette', 'Watch on the Rhine', 'Going My Way',
       'Double Indemnity', 'Gaslight', 'Since You Went Away', 'Wilson',
       'The Lost Weekend', 'Anchors Aweigh', "The Bells of St. Mary's",
       'Mildred Pierce', 'Spellbound', 'The Best Years of Our Lives',
       'Henry V', "It's a Wonderful Life", "The Razor's Edge",
       'The Yearling', "Gentleman's Agreement", "The Bishop's Wife",
       'Crossfire', 'Great Expectations', 'Miracle on 34th Street',
       'Hamlet', 'Johnny Belinda', 'The Red Shoes', 'The Snake Pit',
       'The Treasure of the Sierra Madre', "All the King's Men",
       'Battleground', 'The Heiress', 'A Letter to Three Wives',
       "Twelve O'Clock High", 'All About Eve', 'Born Yesterday',
       'Father of the Bride', "King Solomon's Mines", 'Sunset Boulevard',
       'An American in Paris', 'Decision Before Dawn',
       'A Place in the Sun', 'Quo Vadis', 'A Streetcar Named Desire',
       'The Greatest Show on Earth', 'High Noon', 'Ivanhoe',
       'Moulin Rouge', 'The Quiet Man', 'From Here to Eternity',
       'Julius Caesar', 'The Robe', 'Roman Holiday', 'Shane',
       'On the Waterfront', 'The Caine Mutiny', 'The Country Girl',
       'Seven Brides for Seven Brothers', 'Three Coins in the Fountain',
       'Marty', 'Love Is a Many-Splendored Thing', 'Mister Roberts',
       'Picnic', 'The Rose Tattoo', 'Around the World in 80 Days',
       'Friendly Persuasion', 'Giant', 'The King and I',
       'The Ten Commandments', 'The Bridge on the River Kwai',
       '12 Angry Men', 'Peyton Place', 'Sayonara',
       'Witness for the Prosecution', 'Gigi', 'Auntie Mame',
       'Cat on a Hot Tin Roof', 'The Defiant Ones', 'Separate Tables',
       'Ben-Hur', 'Anatomy of a Murder', 'The Diary of Anne Frank',
       "The Nun's Story", 'Room at the Top', 'The Apartment', 'The Alamo',
       'Elmer Gantry', 'Sons and Lovers', 'The Sundowners',
       'West Side Story', 'Fanny', 'The Guns of Navarone', 'The Hustler',
       'Judgment at Nuremberg', 'Lawrence of Arabia', 'The Longest Day',
       'The Music Man', 'To Kill a Mockingbird', 'Tom Jones',
       'America America', 'How the West Was Won', 'Lilies of the Field',
       'My Fair Lady', 'Becket',
       'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
       'Mary Poppins', 'Zorba the Greek', 'The Sound of Music', 'Darling',
       'Doctor Zhivago', 'Ship of Fools', 'A Thousand Clowns',
       'A Man for All Seasons', 'Alfie',
       'The Russians Are Coming, the Russians Are Coming',
       'The Sand Pebbles', "Who's Afraid of Virginia Woolf?",
       'In the Heat of the Night', 'Bonnie and Clyde', 'Doctor Dolittle',
       'The Graduate', "Guess Who's Coming to Dinner", 'Oliver!',
       'Funny Girl', 'The Lion in Winter', 'Rachel, Rachel',
       'Midnight Cowboy', 'Anne of the Thousand Days',
       'Butch Cassidy and the Sundance Kid', 'Hello, Dolly!', 'Z',
       'Patton', 'Airport', 'Five Easy Pieces', 'Love Story', 'M*A*S*H',
       'The French Connection', 'A Clockwork Orange',
       'Fiddler on the Roof', 'The Last Picture Show',
       'Nicholas and Alexandra', 'The Godfather', 'Cabaret',
       'Deliverance', 'The Emigrants', 'Sounder', 'The Sting',
       'American Graffiti', 'Cries and Whispers', 'The Exorcist',
       'A Touch of Class', 'The Godfather Part II', 'Chinatown',
       'The Conversation', 'Lenny', 'The Towering Inferno',
       "One Flew Over the Cuckoo's Nest", 'Barry Lyndon',
       'Dog Day Afternoon', 'Jaws', 'Nashville', 'Rocky',
       "All the President's Men", 'Bound for Glory', 'Network',
       'Taxi Driver', 'Annie Hall', 'The Goodbye Girl', 'Julia',
       'Star Wars', 'The Turning Point', 'The Deer Hunter', 'Coming Home',
       'Midnight Express', 'An Unmarried Woman', 'Kramer vs. Kramer',
       'All That Jazz', 'Apocalypse Now', 'Breaking Away', 'Norma Rae',
       'Ordinary People', "Coal Miner's Daughter", 'The Elephant Man',
       'Raging Bull', 'Tess', 'Chariots of Fire', 'Atlantic City',
       'On Golden Pond', 'Raiders of the Lost Ark', 'Reds', 'Gandhi',
       'E.T. the Extra-Terrestrial', 'Missing', 'Tootsie', 'The Verdict',
       'Terms of Endearment', 'The Big Chill', 'The Dresser',
       'The Right Stuff', 'Tender Mercies', 'Amadeus',
       'The Killing Fields', 'A Passage to India', 'Places in the Heart',
       "A Soldier's Story", 'Out of Africa', 'The Color Purple',
       'Kiss of the Spider Woman', "Prizzi's Honor", 'Witness', 'Platoon',
       'Children of a Lesser God', 'Hannah and Her Sisters',
       'The Mission', 'A Room with a View', 'The Last Emperor',
       'Broadcast News', 'Fatal Attraction', 'Hope and Glory',
       'Moonstruck', 'Rain Man', 'The Accidental Tourist',
       'Dangerous Liaisons', 'Mississippi Burning', 'Working Girl',
       'Driving Miss Daisy', 'Born on the Fourth of July',
       'Dead Poets Society', 'Field of Dreams', 'My Left Foot',
       'Dances with Wolves', 'Awakenings', 'Ghost',
       'The Godfather Part III', 'Goodfellas', 'The Silence of the Lambs',
       'Beauty and the Beast', 'Bugsy', 'JFK', 'The Prince of Tides',
       'Unforgiven', 'The Crying Game', 'A Few Good Men', 'Howards End',
       'Scent of a Woman', "Schindler's List", 'The Fugitive',
       'In the Name of the Father', 'The Piano', 'The Remains of the Day',
       'Forrest Gump', 'Four Weddings and a Funeral', 'Pulp Fiction',
       'Quiz Show', 'The Shawshank Redemption', 'Braveheart', 'Apollo 13',
       'Babe', 'The Postman (Il Postino)', 'Sense and Sensibility',
       'The English Patient', 'Fargo', 'Jerry Maguire', 'Secrets & Lies',
       'Shine', 'Titanic', 'As Good as It Gets', 'The Full Monty',
       'Good Will Hunting', 'L.A. Confidential', 'Shakespeare in Love',
       'Elizabeth', 'Life Is Beautiful', 'Saving Private Ryan',
       'The Thin Red Line', 'American Beauty', 'The Cider House Rules',
       'The Green Mile', 'The Insider', 'The Sixth Sense', 'Gladiator',
       'Chocolat', 'Crouching Tiger, Hidden Dragon', 'Erin Brockovich',
       'Traffic', 'A Beautiful Mind', 'Gosford Park', 'In the Bedroom',
       'The Lord of the Rings: The Fellowship of the Ring',
       'Moulin Rouge!', 'Chicago', 'Gangs of New York', 'The Hours',
       'The Lord of the Rings: The Two Towers', 'The Pianist',
       'The Lord of the Rings: The Return of the King',
       'Lost in Translation',
       'Master and Commander: The Far Side of the World', 'Mystic River',
       'Seabiscuit', 'Million Dollar Baby', 'The Aviator',
       'Finding Neverland', 'Ray', 'Sideways', 'Crash',
       'Brokeback Mountain', 'Capote', 'Good Night, and Good Luck',
       'Munich', 'The Departed', 'Babel', 'Letters from Iwo Jima',
       'Little Miss Sunshine', 'The Queen', 'No Country for Old Men',
       'Atonement', 'Juno', 'Michael Clayton', 'There Will Be Blood',
       'Slumdog Millionaire', 'The Curious Case of Benjamin Button',
       'Frost/Nixon', 'Milk', 'The Reader', 'The Hurt Locker', 'Avatar',
       'The Blind Side', 'District 9', 'An Education',
       'Inglourious Basterds',
       "Precious: Based on the Novel 'Push' by Sapphire", 'A Serious Man',
       'Up', 'Up in the Air', "The King's Speech", '127 Hours',
       'Black Swan', 'The Fighter', 'Inception', 'The Kids Are All Right',
       'The Social Network', 'Toy Story 3', 'True Grit', "Winter's Bone",
       'The Artist', 'The Descendants',
       'Extremely Loud & Incredibly Close', 'The Help', 'Hugo',
       'Midnight in Paris', 'Moneyball', 'The Tree of Life', 'War Horse',
       'Argo', 'Amour', 'Beasts of the Southern Wild', 'Django Unchained',
       'Life of Pi', 'Lincoln', 'Silver Linings Playbook',
       'Zero Dark Thirty', '12 Years a Slave', 'American Hustle',
       'Captain Phillips', 'Dallas Buyers Club', 'Gravity', 'Her',
       'Nebraska', 'Philomena', 'The Wolf of Wall Street',
       'Birdman or (The Unexpected Virtue of Ignorance)',
       'American Sniper', 'Boyhood', 'The Grand Budapest Hotel',
       'The Imitation Game', 'Selma', 'The Theory of Everything',
       'Whiplash', 'Spotlight', 'The Big Short', 'Bridge of Spies',
       'Brooklyn', 'Mad Max: Fury Road', 'The Martian', 'The Revenant',
       'Room', 'Moonlight', 'Arrival', 'Fences', 'Hacksaw Ridge',
       'Hell or High Water', 'Hidden Figures', 'La La Land', 'Lion',
       'Manchester by the Sea', 'The Shape of Water',
       'Call Me by Your Name', 'Darkest Hour', 'Dunkirk', 'Get Out',
       'Lady Bird', 'Phantom Thread', 'The Post',
       'Three Billboards Outside Ebbing, Missouri', 'Green Book',
       'Black Panther', 'BlacKkKlansman', 'Bohemian Rhapsody',
       'The Favourite', 'Roma', 'Vice', 'Parasite', '1917',
       'Ford v Ferrari', 'The Irishman', 'Jojo Rabbit', 'Joker',
       'Marriage Story', 'Once Upon a Time in Hollywood', 'Nomadland',
       'The Father', 'Judas and the Black Messiah', 'Mank', 'Minari',
       'Promising Young Woman', 'Sound of Metal',
       'The Trial of the Chicago 7'], dtype=object)

In [70]:
df['Film'].value_counts()

Romeo and Juliet            2
Cleopatra                   2
A Star Is Born              2
Little Women                2
Heaven Can Wait             2
                           ..
The Front Page              1
Dunkirk                     1
The Smiling Lieutenant      1
Going My Way                1
In the Heat of the Night    1
Name: Film, Length: 564, dtype: int64

### Создание новой таблицы

In [42]:
# Один из способов создать новую таблицу
df2 = pd.DataFrame({"Column 1": [1, 2, 3], "Column 2": ['red', 'green', 'blue']})

In [43]:
df2['Column 1'].value_counts()

1    1
2    1
3    1
Name: Column 1, dtype: int64

**Упражнение:** Найдите количество уникальных названий фильмов.

In [44]:
len(df['Film'].unique())

564

In [73]:
# А всего фильмов 571
df.shape

(571, 31)

**Упражнение:** Выведите первые 5 по частоте встречаемости фильмы. Если фильмов с одинаковой максимальной частотой встречаемости больше 5, выведите первые 5 среди них.

In [76]:
df['Film'].value_counts()[:5]

Romeo and Juliet    2
Cleopatra           2
A Star Is Born      2
Little Women        2
Heaven Can Wait     2
Name: Film, dtype: int64

**Упражнение:** Выведите количество фильмов, выпущенных после 1957 года.

In [81]:
# Количество фильмов, выпущенных после 1957 года
sum(df['Year of Release'] > 1957)

361

**Упражнение:** Выведите фильмы, выпущенные после 1957 года и имеющие рейтинг строго выше 7.

In [85]:
# Фильмы, выпущенных после 1957 года и имеющих рейтинг выше 7
df[(df['Year of Release'] > 1957) & (df['IMDB Rating'] > 7)]

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID,Year + 100
211,211,Auntie Mame,1958,Jack L. Warner,Nominee,1958,143,"Comedy,Drama,Romance",7.9,"10,825",...,93.0,15.0,Upright,93.0,8232.0,0.0,14.0,1.0,ed3ebe9b-ba2b-4a93-bd71-369b04396fab,2058
212,212,Cat on a Hot Tin Roof,1958,Lawrence Weingarten,Nominee,1958,108,Drama,8.0,"47,222",...,97.0,37.0,Upright,92.0,31748.0,5.0,36.0,1.0,466621aa-287c-4316-9083-74a5fc72a4f6,2058
213,213,The Defiant Ones,1958,Stanley Kramer,Nominee,1958,96,"Crime,Drama",7.6,"14,358",...,83.0,24.0,Upright,87.0,5151.0,4.0,20.0,4.0,45435847-81e6-44f8-891d-59ac0e5bb985,2058
214,214,Separate Tables,1958,Harold Hecht,Nominee,1958,100,"Drama,Romance",7.4,"7,248",...,69.0,16.0,Upright,76.0,1355.0,0.0,11.0,5.0,a19cbb5a-db41-4119-a8ed-c805948873a8,2058
215,215,Ben-Hur,1959,Sam Zimbalist,Winner,1959,212,"Adventure,Drama,History",8.1,"227,894",...,86.0,50.0,Upright,89.0,106187.0,11.0,43.0,7.0,0bb257f6-e9ee-4afd-b8f0-69c2ea1167ae,2059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,565,Judas and the Black Messiah,2020,"Shaka King, Charles D. King, and Ryan Coogler",Nominee,2021,126,"Biography,Drama,History",7.5,"58,996",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cf55544c-fcaa-4b26-9773-52be27359d6f,2121
567,567,Minari,2020,Christina Oh,Nominee,2020,115,Drama,7.5,"57,976",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7262b3a8-214d-4205-985c-70e0860f3236,2120
568,568,Promising Young Woman,2020,"Ben Browning, Ashley Fox, Emerald Fennell, and...",Nominee,2020,113,"Crime,Drama,Thriller",7.5,"122,269",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d64c669b-7a73-496a-bddb-19cb09264371,2120
569,569,Sound of Metal,2020,Bert Hamelinck and Sacha Ben Harroche,Nominee,2019,120,"Drama,Music",7.8,"102,807",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,647357e9-c067-46bd-aaeb-24d4344ec124,2119
570,570,The Trial of the Chicago 7,2020,Marc Platt and Stuart M. Besser,Nominee,2020,129,"Drama,History,Thriller",7.8,"156,283",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cecbca48-f19c-43f4-81d2-da130facda95,2120

**Упражнение:** Выведите фильмы, выпущенные либо после 2000-го, либо ранее 1957-го годов.

In [88]:
# Фильмы, выпущенные после 2000, либо раньше 1957
df[(df['Year of Release'] < 1957) | (df['Year of Release'] > 2000)]

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID,Year + 100
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",...,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067,2027
1,1,7th Heaven,1927/28,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19ed3295-a878-4fd2-8e60-5cd7b5f93dad,2027
2,2,The Racket,1927/28,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3111c2d8-0908-4093-8ff3-99c89f2f2f08,2028
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",...,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236,2029
4,4,Alibi,1928/29,Feature Productions,Nominee,1929,91,"Action,Crime,Romance",5.8,765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609887c2-877c-43a4-b88c-e40e31096a98,2029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,566,Mank,2020,"Ceán Chaffin, Eric Roth, and Douglas Urbanski",Nominee,2020,131,"Biography,Comedy,Drama",6.9,"65,380",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47d4ae4f-e782-4cd9-9508-4a07302b1c1a,2120
567,567,Minari,2020,Christina Oh,Nominee,2020,115,Drama,7.5,"57,976",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7262b3a8-214d-4205-985c-70e0860f3236,2120
568,568,Promising Young Woman,2020,"Ben Browning, Ashley Fox, Emerald Fennell, and...",Nominee,2020,113,"Crime,Drama,Thriller",7.5,"122,269",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d64c669b-7a73-496a-bddb-19cb09264371,2120
569,569,Sound of Metal,2020,Bert Hamelinck and Sacha Ben Harroche,Nominee,2019,120,"Drama,Music",7.8,"102,807",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,647357e9-c067-46bd-aaeb-24d4344ec124,2119
570,570,The Trial of the Chicago 7,2020,Marc Platt and Stuart M. Besser,Nominee,2020,129,"Drama,History,Thriller",7.8,"156,283",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cecbca48-f19c-43f4-81d2-da130facda95,2120

----------

In [94]:
df['IMDB Rating'].sum()

4322.7

In [95]:
df['IMDB Rating'].mean()

7.570402802101572

In [96]:
df['IMDB Rating'].max()

9.3

In [97]:
df['IMDB Rating'].std()

0.5596518456531823

In [98]:
df.describe()

,Unnamed: 0,Year of Release,Movie Time,IMDB Rating,Tomatometer Rating,Tomatometer Count,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Year + 100
count,571.000000,571.000000,571.000000,571.000000,439.000000,439.000000,439.000000,4.390000e+02,439.000000,439.000000,439.000000,571.000000
mean,285.000000,1973.357268,124.894921,7.570403,87.503417,110.697039,82.428246,5.154145e+05,21.861048,98.471526,12.275626,2073.357268
std,164.977776,29.315738,26.322817,0.559652,11.690622,119.541406,10.927897,3.623107e+06,21.615492,107.798554,19.310232,29.315738
min,0.000000,1927.000000,66.000000,5.600000,29.000000,5.000000,21.000000,6.000000e+00,0.000000,3.000000,0.000000,2027.000000
25%,142.500000,1944.000000,107.000000,7.300000,84.000000,25.000000,78.000000,6.637500e+03,5.000000,21.500000,2.000000,2044.000000
50%,285.000000,1972.000000,121.000000,7.600000,91.000000,54.000000,85.000000,3.716600e+04,11.000000,49.000000,5.000000,2072.000000
75%,427.500000,2001.000000,136.500000,7.900000,95.000000,199.000000,90.000000,1.255365e+05,45.000000,163.500000,15.000000,2101.000000
max,570.000000,2021.000000,238.000000,9.300000,100.000000,574.000000,98.000000,3.579764e+07,69.000000,495.000000,182.000000,2121.000000

## 2.3 Работа с пропусками 


Пропуски в данных возникают по разным причинам. Кто-то забыл измерить, записать или в принципе таких данных в природе не существовало. Когда мы будем учить алгоритмы машинного обучения, нам придётся все эти пропуски заполнять. 

Количество пропусков в данных можно узнать с помощью методов `.isna()` или [`.isnull()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isnull.html)

In [92]:
df.isna().sum()

Unnamed: 0                            0
Film                                  0
Oscar Year                            0
Film Studio/Producer(s)               0
Award                                 0
Year of Release                       0
Movie Time                            0
Movie Genre                           0
IMDB Rating                           0
IMDB Votes                            0
Movie Info                          133
Genres                              132
Critic Consensus                    232
Content Rating                      132
Directors                           134
Authors                             134
Actors                              132
Original Release Date               132
Streaming Release Date              133
Production Company                  132
Tomatometer Status                  132
Tomatometer Rating                  132
Tomatometer Count                   132
Audience Status                     135
Audience Rating                     132
Audience Count                      132
Tomatometer Top Critics Count       132
Tomatometer Fresh Critics Count     132
Tomatometer Rotten Critics Count    132
Film ID                               0
Year + 100                            0
dtype: int64

In [ ]:
df.isnull().head() # возвращает True, если в ячейке пропуск, иначе --- False

In [ ]:
df.isnull().sum()  # суммарное количество пропусков в каждом столбце

In [ ]:
# отсортировали число пропусков по убыванию и вывели топ-10 
df.isnull().sum().sort_values(ascending=False).head(10)

Метод `.fillna(что-то)` позволяет заполнить пропуски чем-нибудь нейтральным. Например, посмотрим на колонку `city`. В ней сейчас есть пропуски.

**Упражнение:** Найдите самого популярного автора.

In [101]:
df['Authors'].value_counts()

Ernest Lehman                                             5
George Seaton                                             4
Anthony McCarten                                          3
Robert Riskin                                             3
Casey Robinson                                            3
                                                         ..
Robert E. Sherwood                                        1
Bill Condon                                               1
John Farrow, James Poe, S.J. Perelman                     1
Richard LaGravenese, Steven Soderbergh, Susannah Grant    1
Francis Ford Coppola                                      1
Name: Authors, Length: 397, dtype: int64

**Упражнение:** Найдите среднюю продолжительность фильмов, выпущенных в 2000-м году.

In [108]:
# Средняя продолжительность фильмов, выпущенных в 2000-м году
df2 = df[df['Year of Release'] == 2000]
df2['Movie Time'].mean()

134.8

На последок вот вам __пара панд.__ Ведь именно в честь них (на самом деле в честь panel data) назван пакет pandas.

![](http://www.hughlansdown.com/photos/wildlife/mammals/pair-of-red-pandas.jpg)